### ISSUE TITLE
Custom  iterators with TF 1.12

### ISSUE THREAD

**Issue by statist-bhfz** [rstudio/keras#865]
I got an error
```
Error in py_get_attr_impl(x, name, silent) : 
  AttributeError: module 'kerastools.generator' has no attribute 'iter_generator'
```
when trying to fit model with code like that https://github.com/rstudio/keras/issues/847

It is related to https://github.com/rstudio/keras/issues/682, but I can't find any information about running custom iterators with TF 1.12 or older versions. Should I just upgrade TF to 1.13?

**Comment by statist-bhfz** [comment]
CRAN version of R-keras (2.2.4.1) works with TF 1.12.0 but doesn't work with 1.12.1 or 1.12.3. Github version works with 1.12.1.
