### ISSUE TITLE
How to release GPU memory?

### ISSUE THREAD

**Issue by khawkhaa** [rstudio/keras#739]
I am asking the same question as https://github.com/rstudio/keras/issues/356 which was closed without a solution.

`k_clear_session` does not release my GPU memory. Python Keras https://github.com/keras-team/keras/issues/9379 suggest to use cuda library, but I did not find the equivalent in R Keras. Is there a cuda interface in R? Or do you know others solutions?

**Comment by skeydan** [comment]
You can use reticulate to execute the Python code indicated in that issue, like so:

```
reticulate::py_run_string(
"from numba import cuda;
cuda.select_device(0);
cuda.close()")
```

I tested this and it did indeed release gpu memory.

**Comment by dfalbel** [comment]
By default TensorFlow pre-allocates almost all GPU memory and only releases it when the Python session is closed. When you clear the session in Keras, in practice it will release the GPU memory to TensorFlow and not to the system.

You can configure TF to not pre-allocate the memory using:

```
tf$config$gpu$set_per_process_memory_growth()
```

Read more about this [here](https://www.tensorflow.org/alpha/guide/using_gpu)

**Comment by khawkhaa** [comment]
I want to clear GPU memory after each iteration (in a loop of 10 independent runs) so I can not restart the session because I need to do some statistical on accuracies after all iterations.

When I use 
```
reticulate::py_run_string(
"from numba import cuda;
cuda.select_device(0);
cuda.close()")
```

I have this error: 
```
2019-04-17 18:30:47.059802: E tensorflow/stream_executor/cuda/cuda_driver.cc:1011] could not synchronize on CUDA context: CUDA_ERROR_CONTEXT_IS_DESTROYED: context is destroyed :: *** Begin stack trace ***
	tensorflow::CurrentStackTrace[abi:cxx11]()
	stream_executor::cuda::CUDADriver::SynchronizeContext(stream_executor::cuda::CudaContext*)
	stream_executor::StreamExecutor::SynchronizeAllActivity()
	tensorflow::GPUUtil::SyncAll(tensorflow::Device*)
	tensorflow::BaseGPUDevice::Sync()
	tensorflow::Device::Sync(std::function<void (tensorflow::Status const&)> const&)
	
	
	
	Eigen::ThreadPoolTempl<tensorflow::thread::EigenEnvironment>::WorkerLoop(int)
	std::_Function_handler<void (), tensorflow::thread::EigenEnvironment::CreateThread(std::function<void ()>)::{lambda()#1}>::_M_invoke(std::_Any_data const&)
	
	
	clone
*** End stack trace ***

Error in py_call_impl(callable, dots$args, dots$keywords) : 
  InternalError: GPU sync failed

```

**Comment by skeydan** [comment]
I think it might make sense to ask about that in the TensorFlow repo: https://github.com/tensorflow/tensorflow
and add a link to that issue here.

**Comment by Atan1988** [comment]
I ran into the same issue, and looked into various threads here, and finally solved it by piecing various ideas together. 
I was using tensorflow 1.13.1 and keras 2.4.4, and using tfruns for hyper parameter tuning on a windows 10 machine. 
When turning_runs was running, the memory usage kept increasing, despite both calling k_clearsession and sess$close() (on the tf side).  The python script above is able to release RAM, but after running it, Keras related calls would fail in the same R session. 

In case someone else finds this thread and need some kind of option to move forward, I am listing my solution below:
The solution ended up working is simply using rscript from the callr package to start a new session to train every set of hyper parameter.  The master script looks like this:
`par_list <- list(
  dropout1 = c(0.2, 0.3, 0.4), 
  epochs = 20, 
  patience = 2
) %>% cross()

par_list %>% purrr::map(
  function(x) {
    param <- list(
      train_script = "model script.R",  #this should be able to run standalone to train one model, as in the tfruns tutorial
      train_flags = x, 
      rundir = 'tf models/runs/'
    )
    res <- rscript(script = 'models/tftrain script.R', cmdargs = param, 
            echo = T)
    return(NULL)
  }
)`
since cmdargs are passed as characters, to use the param$train_flags, I needed to do some conversion using rlang: param[[2]] %>% rlang::parse_expr() %>% rlang::eval_tidy()

**Comment by khawkhaa** [comment]
@Atan1988 Thank you for your suggestion.
My solution was to do it in bash to release the GPU memory
```
for i in $(seq 1 20); do
    Rscript.R $i 4
done
```
I will try your solution

**Comment by robertoshea** [comment]
I have cobbled together some scripts (credit to this page  "https://forums.fast.ai/t/tip-clear-tensorflow-gpu-memory/1979/7")  to produce a solution which works with tensorflow 2.0 to clear the gpu. I have tested on my machine (python 3.7, conda tf2.0, nvidia quadro p4000). This clears the python tf session from within the R_session. The function can be placed within a loop in rstudio, saving the need to run an external bash script

`
  py <- function(x){
    reticulate::py_run_string(x)
  }
  py("from keras import backend as K")
  py("from keras.backend.tensorflow_backend import set_session;")
  py("from keras.backend.tensorflow_backend import clear_session;")
  py("from keras.backend.tensorflow_backend import get_session;")
  
  clear_gpu <- function(){
    py("cfg = K.config_pb2.ConfigProto()")
    py("cfg.gpu_options.allow_growth = True")
    py("K.set_session(K.tf.compat.v1.Session(config=cfg))")
    k_clear_session()
  }

#now clear with this command
clear_gpu()
`

**Comment by YHGim** [comment]
> I have cobbled together some scripts (credit to this page "https://forums.fast.ai/t/tip-clear-tensorflow-gpu-memory/1979/7") to produce a solution which works with tensorflow 2.0 to clear the gpu. I have tested on my machine (python 3.7, conda tf2.0, nvidia quadro p4000). This clears the python tf session from within the R_session. The function can be placed within a loop in rstudio, saving the need to run an external bash script
> 
> `
> py <- function(x){
> reticulate::py_run_string(x)
> }
> py("from keras import backend as K")
> py("from keras.backend.tensorflow_backend import set_session;")
> py("from keras.backend.tensorflow_backend import clear_session;")
> py("from keras.backend.tensorflow_backend import get_session;")
> 
> clear_gpu <- function(){
> py("cfg = K.config_pb2.ConfigProto()")
> py("cfg.gpu_options.allow_growth = True")
> py("K.set_session(K.tf.compat.v1.Session(config=cfg))")
> k_clear_session()
> }
> 
> #now clear with this command
> clear_gpu()
> `

For some unknown reason, I get the message

 Error in py_run_string_impl(code, local, convert) : 
  AttributeError: module 'keras.backend' has no attribute 'config_pb2'

**Comment by GreenEric** [comment]
guess shall be rewrite to whatever tf version you are using.

> > #now clear with this command
> > clear_gpu()
> > `
> 
> For some unknown reason, I get the message
> 
> Error in py_run_string_impl(code, local, convert) :
> AttributeError: module 'keras.backend' has no attribute 'config_pb2'
